// Generated by CoffeeScript 1.9.3

/*
  So, the prefix for my profile will be 'ag'
  Lets call the main app: agProfile
 */

(function() {
  angular.module('agProfile', ['ui.router', 'agProfile.controllers', 'agProfile.directives', 'agProfile.services', 'agProfile.constants']).config(function($stateProvider, agDataProvider) {
    $stateProvider.state('profile', {
      templateUrl: './templates/views/view_profile.html'
    }).state('test', {
      templateUrl: './templates/views/view_test.html',
      controller: 'TestController',
      url: '/test'
    });
    return agDataProvider.useLocalData(true);
  });

}).call(this);

//# sourceMappingURL=app.js.map
