// Generated by CoffeeScript 1.9.3

/*
  So, the prefix for my profile will be 'ag'
  Lets call the main app: agProfile
 */

(function() {
  angular.module('agProfile', ['ui.router', 'agProfile.controllers']).config(function($stateProvider) {
    return $stateProvider.state('profile', {
      templateUrl: './templates/views/view_profile.html'
    });
  });

}).call(this);

//# sourceMappingURL=app.js.map
