// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('agProfile.constants', []).constant('agApi', {
    profile: 'http://api.jlabs.co/perkkx/deals'
  }).constant('agDeferredExtender', function(deferred) {
    deferred.promise.success = function(fn) {
      deferred.promise.then(fn, null);
      return deferred;
    };
    deferred.promise.error = function(fn) {
      deferred.promise.then(null, fn);
      return deferred;
    };
    return deferred;
  });

}).call(this);

//# sourceMappingURL=constants.js.map
