// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('agProfile.directives', []).directive('agStarRating', function() {
    return {
      restrict: 'E',
      scope: {
        rating: '=rating'
      },
      templateUrl: './templates/directives/ag_star_rating.html'
    };
  });

}).call(this);

//# sourceMappingURL=directives.js.map
