// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('agProfile.services', []).provider('agData', function() {
    var useLocalData;
    useLocalData = true;
    return {
      useLocalData: function(value) {
        return useLocalData = Boolean(value);
      },
      $get: function($http, $q, agApi, $log, agDeferredExtender, agStats) {
        var createCached, res;
        res = {};
        createCached = function(dt) {
          var obj;
          obj = agDeferredExtender($q.defer());
          obj.resolve(dt);
          return obj.promise;
        };
        if (useLocalData) {
          res.get_profile = function() {
            return createCached(agStats);
          };
        } else {
          res.get_profile = function() {
            return $http.get(agApi.profile);
          };
        }
        return res;
      }
    };
  });

}).call(this);

//# sourceMappingURL=data.js.map
