// Generated by CoffeeScript 1.9.3

/*
  Let's define the controllers module here,
  Then we will call this module every time for the other controllers
  and we make sure this file is loaded first
 */

(function() {
  angular.module('agProfile.controllers', []).controller('MasterController', function($scope, $state, $log) {
    $log.info("Master initialized");
    if (!$state.is('test')) {
      return $state.go('profile');
    }
  }).controller('TestController', function($scope, agData, $log) {
    $scope.rating = 1.5;
    $scope.incRating = function() {
      return $scope.rating += 0.5;
    };
    return agData.get_profile().success(function(data) {
      return $log.debug("Received the data: " + JSON.stringify(data));
    });
  });

}).call(this);

//# sourceMappingURL=master.js.map
