// Generated by CoffeeScript 1.9.3

/*
  Let's define the controllers module here,
  Then we will call this module every time for the other controllers
  and we make sure this file is loaded first
 */

(function() {
  angular.module('agProfile.controllers', []).controller('MasterController', function($scope, $state, $log) {
    $log.info("Master initialized");
    return $state.go('test');
  }).controller('TestController', function($scope) {
    $scope.rating = 1.5;
    return $scope.incRating = function() {
      return $scope.rating += 0.5;
    };
  });

}).call(this);

//# sourceMappingURL=master.js.map
