// Generated by CoffeeScript 1.9.3

/*
  Let's define the controllers module here,
  Then we will call this module every time for the other controllers
  and we make sure this file is loaded first
 */

(function() {
  angular.module('agProfile.controllers', []).controller('MasterController', function($scope, $state, $log) {
    $log.info("Master initialized");
    return $state.go('profile');
  });

}).call(this);

//# sourceMappingURL=master.js.map
