// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('agProfile.controllers').controller('ProfileController', function($scope, agData) {
    $scope.profile_data = {};
    return agData.get_profile().success(function(data) {
      return $scope.profile_data = data;
    });
  });

}).call(this);

//# sourceMappingURL=profile.js.map
